version: '3.9'

services:

  rabbitmq-server:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'sample-rabbitmq-data:/data'
    networks:
      - sample-net


  # test-1:
  #   image: tianon/true
  #   depends_on: ["producer-1", "consumer-1"]

  producer-rb:
    build: .
    command: producer.py
    depends_on:
      - rabbitmq-server
    restart: on-failure
    environment:
      INTERVAL: 0.1
      PREFIX: poffo
      BROKER_QUEUE: poffo_dataqueue_test
      BROKER_EXCHANGE: poffo_exchange_test
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSSWORD: guest
      RABBITMQ_HOST: rabbitmq-server
    networks:
      - sample-net
    volumes:
      - type: bind
        source: ./app
        target: /app


  consumer-rb:
    build: .
    command: consumer.py
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq-server
    restart: on-failure  
    environment:
      INTERVAL: 0.5,1
      BROKER_QUEUE: poffo_dataqueue_test
      BROKER_EXCHANGE: poffo_exchange_test
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSSWORD: guest
      RABBITMQ_HOST: rabbitmq-server
      PREFETCH: 10
    networks:
      - sample-net
    volumes:
      - type: bind
        source: ./app
        target: /app

  producer-sb:
    build: .
    command: producer.py
    restart: on-failure
    env_file:
      - sb.env
    environment:
      INTERVAL: 0.1
      PREFIX: poffo
      BROKER_QUEUE: poffo_datasub_test
      BROKER_EXCHANGE: poffo_exchange_test
    networks:
      - sample-net
    volumes:
      - type: bind
        source: ./app
        target: /app


  consumer-sb:
    build: .
    command: consumer.py
    deploy:
      replicas: 3
    restart: on-failure  
    env_file:
      - sb.env
    environment:
      INTERVAL: 0.5,1
      BROKER_QUEUE: poffo_datasub_test
      BROKER_EXCHANGE: poffo_exchange_test
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSSWORD: guest
      RABBITMQ_HOST: rabbitmq-server
      PREFETCH: 10
    networks:
      - sample-net
    volumes:
      - type: bind
        source: ./app
        target: /app

networks:
  sample-net:
    driver: bridge

volumes:
  sample-rabbitmq-data:      
    driver: local
